import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MeshBackground() {
  return (
    <svg className="fixed inset-0 w-full h-full z-0 pointer-events-none" viewBox="0 0 800 600" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M0 300 Q400 100 800 300 T1600 300"
        stroke="#10b98122"
        strokeWidth="80"
      />
      <path
        d="M0 400 Q400 600 800 400 T1600 400"
        stroke="#f59e0b22"
        strokeWidth="80"
      />
    </svg>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <MeshBackground />
        <div className="relative z-10">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
